import Head from "next/head";
import Main from "../components/Main";
import Sidebar from "../components/Sidebar/Sidebar";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Collabbi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Sidebar />
                <Main />
            </div>
        </div>
    );
}
